apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.9.11
    helm:
      parameters:
        - name: grafana.enabled
          value: "true"
        - name: grafana.persistence.enabled
          value: "true"
        - name: grafana.persistence.size
          value: "5Gi"
        - name: grafana.persistence.type
          value: "pvc"
        - name: grafana.service.type
          value: "NodePort"
        - name: grafana.service.nodePort
          value: "32000"
        - name: promtail.enabled
          value: "true"
        - name: prometheus.enabled
          value: "true"
        - name: prometheus.alertmanager.persistentVolume.enabled
          value: "false"
        - name: prometheus.server.persistentVolume.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true