---
- name: Initialize Kubernetes Master
  hosts: master
  become: true
  tasks:
    - name: Check if Kubernetes is already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: k8s_initialized

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_host }}
      when: not k8s_initialized.stat.exists
      register: kubeadm_init_output

    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu

    - name: Install Flannel Pod Network
      become: false
      command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      when: kubeadm_init_output.changed

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Set join command fact
      set_fact:
        join_cmd: "{{ join_command.stdout }}"

- name: Join Worker Nodes to Cluster
  hosts: workers
  become: true
  tasks:
    - name: Check if node is already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: node_joined

    - name: Join the node to cluster
      command: "{{ hostvars[groups['master'][0]]['join_cmd'] }}"
      when: not node_joined.stat.exists