apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meme-test
  template:
    metadata:
      labels:
        app: meme-test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: meme-test-svc
  namespace: default
spec:
  selector:
    app: meme-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meme-test-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: meme.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: meme-test-svc
            port:
              number: 80